[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false

[browser]
serverAddress = "127.0.0.1"
serverPort = 8501

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
